"""
WordPress REST API 客户端 — 通过自定义端点发布社媒内容

使用 CrossBorder Social Publisher 插件 (cb-social-publisher.php)。
API Key 认证，创建 draft 帖子 + 图片上传。
"""

import httpx
from typing import Optional

WORDPRESS_URL = "http://localhost:8080"
WORDPRESS_API_KEY = "cb-social-key-2026"
CB_API_BASE = f"{WORDPRESS_URL}/index.php?rest_route=/cb/v1"


class WordPressClient:
    """WordPress 自定义 REST API 封装"""

    def __init__(self, base_url: str = WORDPRESS_URL, api_key: str = WORDPRESS_API_KEY):
        self.base_url = base_url.rstrip("/")
        self.api_key = api_key
        self._client: Optional[httpx.AsyncClient] = None

    @property
    def client(self) -> httpx.AsyncClient:
        if self._client is None:
            self._client = httpx.AsyncClient(timeout=30)
        return self._client

    def _headers(self) -> dict:
        return {
            "X-CB-API-Key": self.api_key,
            "Content-Type": "application/json",
        }

    async def test_connection(self) -> bool:
        """测试连接是否正常"""
        try:
            resp = await self.client.get(self.base_url)
            return resp.status_code in (200, 302, 301)
        except Exception:
            return False

    async def create_post(self, title: str, content: str,
                          status: str = "draft") -> dict:
        """创建 WordPress 帖子"""
        resp = await self.client.post(
            f"{CB_API_BASE}/publish",
            headers=self._headers(),
            json={"title": title, "content": content, "status": status},
        )
        if resp.status_code == 200:
            return resp.json()
        raise Exception(f"WordPress API error {resp.status_code}: {resp.text[:200]}")

    async def upload_image(self, image_url: str) -> Optional[dict]:
        """上传图片到 WordPress 媒体库"""
        try:
            resp = await self.client.post(
                f"{CB_API_BASE}/upload-image",
                headers=self._headers(),
                json={"image_url": image_url},
            )
            if resp.status_code == 200:
                return resp.json()
        except Exception:
            pass
        return None

    async def publish_social_post(self, platform: str, copy_text: str,
                                  hashtags: list[str], image_urls: list[str],
                                  product_name: str = "") -> dict:
        """发布社媒帖子到 WordPress"""

        # 上传第一张有效图片
        media_info = None
        for url in image_urls:
            if url and not url.startswith("[image-gen]"):
                media_info = await self.upload_image(url)
                if media_info:
                    break

        # 构建帖子内容
        hashtag_str = " ".join(f"#{t}" for t in hashtags)
        img_html = ""
        if media_info:
            img_html = f'<img src="{media_info["url"]}" alt="{product_name}" /><br/><br/>'

        content = f"""{img_html}<p>{copy_text}</p>
<p>{hashtag_str}</p>
<p><em>Platform: {platform} | Auto-generated by CrossBorder Agents</em></p>"""

        title = f"{product_name} - {platform.title()}" if product_name else f"Social Post - {platform.title()}"

        post = await self.create_post(title=title, content=content)

        return {
            "wordpress_post_id": post["id"],
            "wordpress_url": post["url"],
            "edit_url": post.get("edit_url", ""),
            "status": post["status"],
            "platform": platform,
            "image_id": media_info.get("id") if media_info else None,
        }


wp_client: Optional[WordPressClient] = None


def get_wp_client() -> WordPressClient:
    global wp_client
    if wp_client is None:
        wp_client = WordPressClient()
    return wp_client

